/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/apis/apinto/v1"
	versioned "github.com/eolinker/apinto-ingress-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/eolinker/apinto-ingress-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/eolinker/apinto-ingress-controller/pkg/client/listers/apinto/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AuthInformer provides access to a shared informer and lister for
// Auths.
type AuthInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AuthLister
}

type authInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAuthInformer constructs a new informer for Auth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAuthInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAuthInformer constructs a new informer for Auth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().Auths(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().Auths(namespace).Watch(context.TODO(), options)
			},
		},
		&apintov1.Auth{},
		resyncPeriod,
		indexers,
	)
}

func (f *authInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAuthInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *authInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apintov1.Auth{}, f.defaultInformer)
}

func (f *authInformer) Lister() v1.AuthLister {
	return v1.NewAuthLister(f.Informer().GetIndexer())
}
