apiVersion: v1
kind: Service
metadata:
  name: apinto-admission-server
  labels:
    app: apinto-admission-server
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: apinto-ingress-controller