/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// AuthListerExpansion allows custom methods to be added to
// AuthLister.
type AuthListerExpansion interface{}

// AuthNamespaceListerExpansion allows custom methods to be added to
// AuthNamespaceLister.
type AuthNamespaceListerExpansion interface{}

// DiscoveryListerExpansion allows custom methods to be added to
// DiscoveryLister.
type DiscoveryListerExpansion interface{}

// DiscoveryNamespaceListerExpansion allows custom methods to be added to
// DiscoveryNamespaceLister.
type DiscoveryNamespaceListerExpansion interface{}

// OutputListerExpansion allows custom methods to be added to
// OutputLister.
type OutputListerExpansion interface{}

// OutputNamespaceListerExpansion allows custom methods to be added to
// OutputNamespaceLister.
type OutputNamespaceListerExpansion interface{}

// RouterListerExpansion allows custom methods to be added to
// RouterLister.
type RouterListerExpansion interface{}

// RouterNamespaceListerExpansion allows custom methods to be added to
// RouterNamespaceLister.
type RouterNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// SettingListerExpansion allows custom methods to be added to
// SettingLister.
type SettingListerExpansion interface{}

// SettingNamespaceListerExpansion allows custom methods to be added to
// SettingNamespaceLister.
type SettingNamespaceListerExpansion interface{}

// UpstreamListerExpansion allows custom methods to be added to
// UpstreamLister.
type UpstreamListerExpansion interface{}

// UpstreamNamespaceListerExpansion allows custom methods to be added to
// UpstreamNamespaceLister.
type UpstreamNamespaceListerExpansion interface{}
