/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/apis/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDiscoveries implements DiscoveryInterface
type FakeDiscoveries struct {
	Fake *FakeApintoV1
	ns   string
}

var discoveriesResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "discoveries"}

var discoveriesKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "Discovery"}

// Get takes name of the discovery, and returns the corresponding discovery object, and an error if there is any.
func (c *FakeDiscoveries) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.Discovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(discoveriesResource, c.ns, name), &apintov1.Discovery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Discovery), err
}

// List takes label and field selectors, and returns the list of Discoveries that match those selectors.
func (c *FakeDiscoveries) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.DiscoveryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(discoveriesResource, discoveriesKind, c.ns, opts), &apintov1.DiscoveryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.DiscoveryList{ListMeta: obj.(*apintov1.DiscoveryList).ListMeta}
	for _, item := range obj.(*apintov1.DiscoveryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested discoveries.
func (c *FakeDiscoveries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(discoveriesResource, c.ns, opts))

}

// Create takes the representation of a discovery and creates it.  Returns the server's representation of the discovery, and an error, if there is any.
func (c *FakeDiscoveries) Create(ctx context.Context, discovery *apintov1.Discovery, opts v1.CreateOptions) (result *apintov1.Discovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(discoveriesResource, c.ns, discovery), &apintov1.Discovery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Discovery), err
}

// Update takes the representation of a discovery and updates it. Returns the server's representation of the discovery, and an error, if there is any.
func (c *FakeDiscoveries) Update(ctx context.Context, discovery *apintov1.Discovery, opts v1.UpdateOptions) (result *apintov1.Discovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(discoveriesResource, c.ns, discovery), &apintov1.Discovery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Discovery), err
}

// Delete takes name of the discovery and deletes it. Returns an error if one occurs.
func (c *FakeDiscoveries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(discoveriesResource, c.ns, name, opts), &apintov1.Discovery{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDiscoveries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(discoveriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.DiscoveryList{})
	return err
}

// Patch applies the patch and returns the patched discovery.
func (c *FakeDiscoveries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.Discovery, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(discoveriesResource, c.ns, name, pt, data, subresources...), &apintov1.Discovery{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Discovery), err
}
