/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/apis/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuths implements AuthInterface
type FakeAuths struct {
	Fake *FakeApintoV1
	ns   string
}

var authsResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "auths"}

var authsKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "Auth"}

// Get takes name of the auth, and returns the corresponding auth object, and an error if there is any.
func (c *FakeAuths) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.Auth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(authsResource, c.ns, name), &apintov1.Auth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Auth), err
}

// List takes label and field selectors, and returns the list of Auths that match those selectors.
func (c *FakeAuths) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.AuthList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(authsResource, authsKind, c.ns, opts), &apintov1.AuthList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.AuthList{ListMeta: obj.(*apintov1.AuthList).ListMeta}
	for _, item := range obj.(*apintov1.AuthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested auths.
func (c *FakeAuths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(authsResource, c.ns, opts))

}

// Create takes the representation of a auth and creates it.  Returns the server's representation of the auth, and an error, if there is any.
func (c *FakeAuths) Create(ctx context.Context, auth *apintov1.Auth, opts v1.CreateOptions) (result *apintov1.Auth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(authsResource, c.ns, auth), &apintov1.Auth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Auth), err
}

// Update takes the representation of a auth and updates it. Returns the server's representation of the auth, and an error, if there is any.
func (c *FakeAuths) Update(ctx context.Context, auth *apintov1.Auth, opts v1.UpdateOptions) (result *apintov1.Auth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(authsResource, c.ns, auth), &apintov1.Auth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Auth), err
}

// Delete takes name of the auth and deletes it. Returns an error if one occurs.
func (c *FakeAuths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(authsResource, c.ns, name, opts), &apintov1.Auth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(authsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.AuthList{})
	return err
}

// Patch applies the patch and returns the patched auth.
func (c *FakeAuths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.Auth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(authsResource, c.ns, name, pt, data, subresources...), &apintov1.Auth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.Auth), err
}
