/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/eolinker/apinto-ingress-controller/pkg/apis/apinto/v1"
	scheme "github.com/eolinker/apinto-ingress-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AuthsGetter has a method to return a AuthInterface.
// A group's client should implement this interface.
type AuthsGetter interface {
	Auths(namespace string) AuthInterface
}

// AuthInterface has methods to work with Auth resources.
type AuthInterface interface {
	Create(ctx context.Context, auth *v1.Auth, opts metav1.CreateOptions) (*v1.Auth, error)
	Update(ctx context.Context, auth *v1.Auth, opts metav1.UpdateOptions) (*v1.Auth, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Auth, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AuthList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Auth, err error)
	AuthExpansion
}

// auths implements AuthInterface
type auths struct {
	client rest.Interface
	ns     string
}

// newAuths returns a Auths
func newAuths(c *ApintoV1Client, namespace string) *auths {
	return &auths{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the auth, and returns the corresponding auth object, and an error if there is any.
func (c *auths) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Auth, err error) {
	result = &v1.Auth{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auths").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Auths that match those selectors.
func (c *auths) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AuthList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AuthList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("auths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested auths.
func (c *auths) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("auths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a auth and creates it.  Returns the server's representation of the auth, and an error, if there is any.
func (c *auths) Create(ctx context.Context, auth *v1.Auth, opts metav1.CreateOptions) (result *v1.Auth, err error) {
	result = &v1.Auth{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("auths").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(auth).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a auth and updates it. Returns the server's representation of the auth, and an error, if there is any.
func (c *auths) Update(ctx context.Context, auth *v1.Auth, opts metav1.UpdateOptions) (result *v1.Auth, err error) {
	result = &v1.Auth{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("auths").
		Name(auth.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(auth).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the auth and deletes it. Returns an error if one occurs.
func (c *auths) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auths").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *auths) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("auths").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched auth.
func (c *auths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Auth, err error) {
	result = &v1.Auth{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("auths").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
