/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApintoSettings implements ApintoSettingInterface
type FakeApintoSettings struct {
	Fake *FakeApintoV1
	ns   string
}

var apintosettingsResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "apintosettings"}

var apintosettingsKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "ApintoSetting"}

// Get takes name of the apintoSetting, and returns the corresponding apintoSetting object, and an error if there is any.
func (c *FakeApintoSettings) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.ApintoSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apintosettingsResource, c.ns, name), &apintov1.ApintoSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoSetting), err
}

// List takes label and field selectors, and returns the list of ApintoSettings that match those selectors.
func (c *FakeApintoSettings) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.ApintoSettingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apintosettingsResource, apintosettingsKind, c.ns, opts), &apintov1.ApintoSettingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.ApintoSettingList{ListMeta: obj.(*apintov1.ApintoSettingList).ListMeta}
	for _, item := range obj.(*apintov1.ApintoSettingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apintoSettings.
func (c *FakeApintoSettings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apintosettingsResource, c.ns, opts))

}

// Create takes the representation of a apintoSetting and creates it.  Returns the server's representation of the apintoSetting, and an error, if there is any.
func (c *FakeApintoSettings) Create(ctx context.Context, apintoSetting *apintov1.ApintoSetting, opts v1.CreateOptions) (result *apintov1.ApintoSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apintosettingsResource, c.ns, apintoSetting), &apintov1.ApintoSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoSetting), err
}

// Update takes the representation of a apintoSetting and updates it. Returns the server's representation of the apintoSetting, and an error, if there is any.
func (c *FakeApintoSettings) Update(ctx context.Context, apintoSetting *apintov1.ApintoSetting, opts v1.UpdateOptions) (result *apintov1.ApintoSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apintosettingsResource, c.ns, apintoSetting), &apintov1.ApintoSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoSetting), err
}

// Delete takes name of the apintoSetting and deletes it. Returns an error if one occurs.
func (c *FakeApintoSettings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apintosettingsResource, c.ns, name, opts), &apintov1.ApintoSetting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApintoSettings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apintosettingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.ApintoSettingList{})
	return err
}

// Patch applies the patch and returns the patched apintoSetting.
func (c *FakeApintoSettings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.ApintoSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apintosettingsResource, c.ns, name, pt, data, subresources...), &apintov1.ApintoSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoSetting), err
}
