/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApintoGlobalSettings implements ApintoGlobalSettingInterface
type FakeApintoGlobalSettings struct {
	Fake *FakeApintoV1
	ns   string
}

var apintoglobalsettingsResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "apintoglobalsettings"}

var apintoglobalsettingsKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "ApintoGlobalSetting"}

// Get takes name of the apintoGlobalSetting, and returns the corresponding apintoGlobalSetting object, and an error if there is any.
func (c *FakeApintoGlobalSettings) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.ApintoGlobalSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apintoglobalsettingsResource, c.ns, name), &apintov1.ApintoGlobalSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoGlobalSetting), err
}

// List takes label and field selectors, and returns the list of ApintoGlobalSettings that match those selectors.
func (c *FakeApintoGlobalSettings) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.ApintoGlobalSettingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apintoglobalsettingsResource, apintoglobalsettingsKind, c.ns, opts), &apintov1.ApintoGlobalSettingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.ApintoGlobalSettingList{ListMeta: obj.(*apintov1.ApintoGlobalSettingList).ListMeta}
	for _, item := range obj.(*apintov1.ApintoGlobalSettingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apintoGlobalSettings.
func (c *FakeApintoGlobalSettings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apintoglobalsettingsResource, c.ns, opts))

}

// Create takes the representation of a apintoGlobalSetting and creates it.  Returns the server's representation of the apintoGlobalSetting, and an error, if there is any.
func (c *FakeApintoGlobalSettings) Create(ctx context.Context, apintoGlobalSetting *apintov1.ApintoGlobalSetting, opts v1.CreateOptions) (result *apintov1.ApintoGlobalSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apintoglobalsettingsResource, c.ns, apintoGlobalSetting), &apintov1.ApintoGlobalSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoGlobalSetting), err
}

// Update takes the representation of a apintoGlobalSetting and updates it. Returns the server's representation of the apintoGlobalSetting, and an error, if there is any.
func (c *FakeApintoGlobalSettings) Update(ctx context.Context, apintoGlobalSetting *apintov1.ApintoGlobalSetting, opts v1.UpdateOptions) (result *apintov1.ApintoGlobalSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apintoglobalsettingsResource, c.ns, apintoGlobalSetting), &apintov1.ApintoGlobalSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoGlobalSetting), err
}

// Delete takes name of the apintoGlobalSetting and deletes it. Returns an error if one occurs.
func (c *FakeApintoGlobalSettings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apintoglobalsettingsResource, c.ns, name, opts), &apintov1.ApintoGlobalSetting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApintoGlobalSettings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apintoglobalsettingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.ApintoGlobalSettingList{})
	return err
}

// Patch applies the patch and returns the patched apintoGlobalSetting.
func (c *FakeApintoGlobalSettings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.ApintoGlobalSetting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apintoglobalsettingsResource, c.ns, name, pt, data, subresources...), &apintov1.ApintoGlobalSetting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoGlobalSetting), err
}
