/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApintoAuths implements ApintoAuthInterface
type FakeApintoAuths struct {
	Fake *FakeApintoV1
	ns   string
}

var apintoauthsResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "apintoauths"}

var apintoauthsKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "ApintoAuth"}

// Get takes name of the apintoAuth, and returns the corresponding apintoAuth object, and an error if there is any.
func (c *FakeApintoAuths) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.ApintoAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apintoauthsResource, c.ns, name), &apintov1.ApintoAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoAuth), err
}

// List takes label and field selectors, and returns the list of ApintoAuths that match those selectors.
func (c *FakeApintoAuths) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.ApintoAuthList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apintoauthsResource, apintoauthsKind, c.ns, opts), &apintov1.ApintoAuthList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.ApintoAuthList{ListMeta: obj.(*apintov1.ApintoAuthList).ListMeta}
	for _, item := range obj.(*apintov1.ApintoAuthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apintoAuths.
func (c *FakeApintoAuths) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apintoauthsResource, c.ns, opts))

}

// Create takes the representation of a apintoAuth and creates it.  Returns the server's representation of the apintoAuth, and an error, if there is any.
func (c *FakeApintoAuths) Create(ctx context.Context, apintoAuth *apintov1.ApintoAuth, opts v1.CreateOptions) (result *apintov1.ApintoAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apintoauthsResource, c.ns, apintoAuth), &apintov1.ApintoAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoAuth), err
}

// Update takes the representation of a apintoAuth and updates it. Returns the server's representation of the apintoAuth, and an error, if there is any.
func (c *FakeApintoAuths) Update(ctx context.Context, apintoAuth *apintov1.ApintoAuth, opts v1.UpdateOptions) (result *apintov1.ApintoAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apintoauthsResource, c.ns, apintoAuth), &apintov1.ApintoAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoAuth), err
}

// Delete takes name of the apintoAuth and deletes it. Returns an error if one occurs.
func (c *FakeApintoAuths) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apintoauthsResource, c.ns, name, opts), &apintov1.ApintoAuth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApintoAuths) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apintoauthsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.ApintoAuthList{})
	return err
}

// Patch applies the patch and returns the patched apintoAuth.
func (c *FakeApintoAuths) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.ApintoAuth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apintoauthsResource, c.ns, name, pt, data, subresources...), &apintov1.ApintoAuth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoAuth), err
}
