/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApintoUpstreams implements ApintoUpstreamInterface
type FakeApintoUpstreams struct {
	Fake *FakeApintoV1
	ns   string
}

var apintoupstreamsResource = schema.GroupVersionResource{Group: "apinto.com", Version: "v1", Resource: "apintoupstreams"}

var apintoupstreamsKind = schema.GroupVersionKind{Group: "apinto.com", Version: "v1", Kind: "ApintoUpstream"}

// Get takes name of the apintoUpstream, and returns the corresponding apintoUpstream object, and an error if there is any.
func (c *FakeApintoUpstreams) Get(ctx context.Context, name string, options v1.GetOptions) (result *apintov1.ApintoUpstream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apintoupstreamsResource, c.ns, name), &apintov1.ApintoUpstream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoUpstream), err
}

// List takes label and field selectors, and returns the list of ApintoUpstreams that match those selectors.
func (c *FakeApintoUpstreams) List(ctx context.Context, opts v1.ListOptions) (result *apintov1.ApintoUpstreamList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apintoupstreamsResource, apintoupstreamsKind, c.ns, opts), &apintov1.ApintoUpstreamList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &apintov1.ApintoUpstreamList{ListMeta: obj.(*apintov1.ApintoUpstreamList).ListMeta}
	for _, item := range obj.(*apintov1.ApintoUpstreamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apintoUpstreams.
func (c *FakeApintoUpstreams) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apintoupstreamsResource, c.ns, opts))

}

// Create takes the representation of a apintoUpstream and creates it.  Returns the server's representation of the apintoUpstream, and an error, if there is any.
func (c *FakeApintoUpstreams) Create(ctx context.Context, apintoUpstream *apintov1.ApintoUpstream, opts v1.CreateOptions) (result *apintov1.ApintoUpstream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apintoupstreamsResource, c.ns, apintoUpstream), &apintov1.ApintoUpstream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoUpstream), err
}

// Update takes the representation of a apintoUpstream and updates it. Returns the server's representation of the apintoUpstream, and an error, if there is any.
func (c *FakeApintoUpstreams) Update(ctx context.Context, apintoUpstream *apintov1.ApintoUpstream, opts v1.UpdateOptions) (result *apintov1.ApintoUpstream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apintoupstreamsResource, c.ns, apintoUpstream), &apintov1.ApintoUpstream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoUpstream), err
}

// Delete takes name of the apintoUpstream and deletes it. Returns an error if one occurs.
func (c *FakeApintoUpstreams) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apintoupstreamsResource, c.ns, name, opts), &apintov1.ApintoUpstream{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApintoUpstreams) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apintoupstreamsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apintov1.ApintoUpstreamList{})
	return err
}

// Patch applies the patch and returns the patched apintoUpstream.
func (c *FakeApintoUpstreams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apintov1.ApintoUpstream, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apintoupstreamsResource, c.ns, name, pt, data, subresources...), &apintov1.ApintoUpstream{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apintov1.ApintoUpstream), err
}
