apiVersion: apinto.com/v1beta
kind: ApintoDiscovery
metadata:
  name: test-ad
spec:
  - name: demo_ad_1
    driver: consul
    scheme: http
    config:
      address: ["127.0.0.1:8501","127.0.0.1:8500"]
      params:
        token: "a92316d8-5c99-4fa0-b4cd-30b9e66718aa"
        namespace: default
  - name: demo_ad_2
    driver: static
    scheme: http
    health:
      scheme: http
      method: GET
      url: http://test.com/health/check
      success_code: 200
      period: 30
      timeout: 3000
    