apiVersion: apinto.com/v1beta
kind: ApintoOutout
metadata:
  name: fileaccesslog
spec:
  name: fileAccessLog
  driver: file
  file:
    config:
      dir: work
      file: access.log
      period: day
      expire: 3
      formatter:
        fields:
          - "$http_hedaer_text"
          - "$read_ip"
          - "$service"
          - "$proxy_header_authorization"
          - "$proxy_uri"