apiVersion: apinto.com/v1beta
kind: ApintoOutout
metadata:
  name: apinto.output
spec:
  kafka_output:
    - name: kafkaLog1
      driver: kafka_output
      config:
        topic: "test1"
        address: 127.0.0.1
        version: 2.0.0.2
        partition_type: "random"
        type: "json"
        formatter:
          fields: []
    - name: kafkaLog2
      driver: kafka_output
      config:
        topic: "test2"
        address: 127.0.0.2
        partition_type: "hash"
        partition_key: "$read_ip"
        formatter:
          fields: []
    - name: kafkaLog3
      driver: kafka_output
      config:
        topic: "test3"
        address: 127.0.0.3
        partition_type: "manual"
        partition: 0
        formatter:
          fields: []
  nsqd:
    - name: nsqdLog
      driver: nsqd
      config:
        topic: "test"
        address:
          - 127.0.0.1
        formatter:
          fields: []
  http_output:
    - name: httpAccessLog
      driver: http_output
      config:
        url: http://127.0.0.1
        method: POST
        type: json
        formatter:
          fields: #当长度为0时默认输出所有字段
            - "$http_hedaer_text"
            - "$read_ip"
            - "$service"
            - "$proxy_header_authorization"
            - "$proxy_uri"
            - "$proxy_scheme" # http
            - "$cookie"
            - "$cookie_eolinker"
            - "$service"
            - "@proxys"
          proxys:
            - "$header"
  file_output:
    - name: fileAccessLog
      driver: file_output
      config:
        dir: work
        file: access.log
        period: day
        expire: 3
        formatter:
          fields:
            - "$http_hedaer_text"
            - "$read_ip"
            - "$service"
            - "$proxy_header_authorization"
            - "$proxy_uri"



