apiVersion: apinto.com/v1beta
kind: ApintoRouter
metadata:
  name: apinto.router
spec:
  name: apinto.router # 路由名称
  listen: 8080    # 监听端口
  driver: http # 驱动
  protocol: http
  method:
    - GET
  rules:      # 规则列表
    - location: "/demo"  # 匹配路径，该示例为前缀匹配，即只要前缀是 “/” 的路径都可匹配成功
  target: demo-anonymous@service    # 目标服务ID，格式为：{服务名称}@service