apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: apinto-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: apinto-ingress-controller
    spec:
      containers:
        - image: eolinker/apinto-ingress-controller:latest
          imagePullPolicy: IfNotPresent
          name: ingress-controller
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8443
              hostPort: 8443
          volumeMounts:
            - mountPath: /etc/ingress/config.yaml
              name: apinto-ingress-configmap
              subPath: config.yaml
              readOnly: true
            - name: admission-webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: apinto-ingress-configmap
          configMap:
            name: apinto-ingress-conf
        - name: admission-webhook-certs
          secret:
            secretName: admission-webhook-certs
# 若不挂载config_map以及secret文件，则将会使用默认的配置文件以及证书
# 默认的apinto集群地址是"http://apinto-svc.default.svc:31094“ （默认命名空间下的apinto-svc服务。）
# 默认http监听端口：8080 https监听端口：8443
#默认证书对应的（用于配置ValidatingWebhookConfiguration资源）CA_Bundle为：LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVVzJSNUhONWtMYjlDamdCaVB6c3ZUY3hQUG1vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xqRXNNQ29HQTFVRUF3d2pZWEJwYm5SdkxXRmtiV2x6YzJsdmJpMXpaWEoyWlhJdVpHVm1ZWFZzZEM1egpkbU13SUJjTk1qSXdNekl5TURNek1EUTBXaGdQTXpBeU1UQTNNak13TXpNd05EUmFNQzR4TERBcUJnTlZCQU1NCkkyRndhVzUwYnkxaFpHMXBjM05wYjI0dGMyVnlkbVZ5TG1SbFptRjFiSFF1YzNaak1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXpWODNlRDdlMWlwZGMwSFlDaDIvamVjV0YyNENUbG9ydmFkVQp6R1hrRzA1QVU2T2NIOE1UNUlYaithaFpqYnBTTmVaTUNXNFZOZkZDNk1pOUxCZDBKc3o3TFErUThqTDFNY2loCjhud1FyLzFsSHhXL3Arb3cvLzJGWllwVXg0bFZxR3pPTlZ6aSsrRDJnOXBhVmU2bEdVZ0tLU053K0R4aWxYL1MKdEZrT2FjL3dBeW9WUDlTQlZDM3J4emtWRUdVRnFtREJJTkZkSWVjTEQwUlFzLzVYZkJzMEhiSExoTllrLzcvRQoxd3hUelUyT1hNMzJqUDVCcFpPK3dkajJGMjBVTTR3ZHp0TTVpdGFyRFQzOHhRUUpzem5QNHJyYmdqVlVkcHFOCkpTa21yeWsrREtpeGpYR2V1S0NvMGE3WEJXZW5laHhNZVh6MUZjMzZiYVNzUm9qekNRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVWks0QkFhdUw3a3lISlpOejBYeWdJN3BNdEx3d0h3WURWUjBqQkJnd0ZvQVVaSzRCQWF1TAo3a3lISlpOejBYeWdJN3BNdEx3d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFudDhxWW1waVpiWVhJMmp4NnpocnpBS2FCUVQrTjYycjBoZnFGNmUydGo5WVZaRUlvN0xCSmJRZmZia08KVGQ1bGFqc0piUzFLZFVTTndvTkxJZ2FqNmNMSkRTZFFWdTJSNUp2d2l4VXlxdnBDQU0vWWlSakVhdGVubzJ5cApFNElXUHVIdllpbnEydDI5K1ExZmR0Vkh2NEttazBGemlDSW4veVVqTjJma3JDdTFzTWt4V1hBbWhVKzlEWmF4CmF2ODVLay9aRWZEMlNlbkRUTjlaSS9oQWFxMUNCVHoyTGRwY1AvY2U4QXVGbm5RelNibHpTTjZFMHpZaWxSM3cKbTlvM2Uwb0RBTmdERldKbEg1SmMwVlpoQlVQcU9qemJ6dmIxckkrVUFLd21LNVZUY2lYZmV6N0NIMWtnbXk1SgpWelJkQkQ3Mitmb3ZqNHFGcG1LRUc2Z0JFQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#默认证书配置的CN为：`CN=apinto-admission-server.default.svc`