apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: apinto-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: apinto-ingress-controller
    spec:
      containers:
        - image: docker.eolink.com/product/demo_apinto_controller:0.1.0
          imagePullPolicy: Never
          name: ingress-controller
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8443
              hostPort: 8443
          volumeMounts:
            - mountPath: /etc/ingress/config.yaml
              name: apinto-ingress-configmap
              subPath: config.yaml
              readOnly: true
            - name: admission-webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          volumes:
            - name: apinto-ingress-configmap
              configMap:
                name: apinto_ingress_conf
            - name: admission-webhook-certs
              secret:
                secretName: admission-webhook-certs
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name