/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ApintoAuthListerExpansion allows custom methods to be added to
// ApintoAuthLister.
type ApintoAuthListerExpansion interface{}

// ApintoAuthNamespaceListerExpansion allows custom methods to be added to
// ApintoAuthNamespaceLister.
type ApintoAuthNamespaceListerExpansion interface{}

// ApintoDiscoveryListerExpansion allows custom methods to be added to
// ApintoDiscoveryLister.
type ApintoDiscoveryListerExpansion interface{}

// ApintoDiscoveryNamespaceListerExpansion allows custom methods to be added to
// ApintoDiscoveryNamespaceLister.
type ApintoDiscoveryNamespaceListerExpansion interface{}

// ApintoGlobalSettingListerExpansion allows custom methods to be added to
// ApintoGlobalSettingLister.
type ApintoGlobalSettingListerExpansion interface{}

// ApintoGlobalSettingNamespaceListerExpansion allows custom methods to be added to
// ApintoGlobalSettingNamespaceLister.
type ApintoGlobalSettingNamespaceListerExpansion interface{}

// ApintoOutputListerExpansion allows custom methods to be added to
// ApintoOutputLister.
type ApintoOutputListerExpansion interface{}

// ApintoOutputNamespaceListerExpansion allows custom methods to be added to
// ApintoOutputNamespaceLister.
type ApintoOutputNamespaceListerExpansion interface{}

// ApintoRouterListerExpansion allows custom methods to be added to
// ApintoRouterLister.
type ApintoRouterListerExpansion interface{}

// ApintoRouterNamespaceListerExpansion allows custom methods to be added to
// ApintoRouterNamespaceLister.
type ApintoRouterNamespaceListerExpansion interface{}

// ApintoServiceListerExpansion allows custom methods to be added to
// ApintoServiceLister.
type ApintoServiceListerExpansion interface{}

// ApintoServiceNamespaceListerExpansion allows custom methods to be added to
// ApintoServiceNamespaceLister.
type ApintoServiceNamespaceListerExpansion interface{}

// ApintoUpstreamListerExpansion allows custom methods to be added to
// ApintoUpstreamLister.
type ApintoUpstreamListerExpansion interface{}

// ApintoUpstreamNamespaceListerExpansion allows custom methods to be added to
// ApintoUpstreamNamespaceLister.
type ApintoUpstreamNamespaceListerExpansion interface{}
