apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apintoupstreams.apinto.com
spec:
  group: apinto.com
  scope: Namespaced
  names:
    plural: apintoglobalsettings
    singular: apintoglobalsetting
    kind: ApintoGlobalSetting
    shortNames:
      - ags
  versions:
    - name: v1beta
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                plugins:
                  type: array
                  items:
                    type: object
                    required: ["id","name","type","status"]
                    properties:
                      id:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                      "type":
                        type: string
                        enum: ["service","router","upstream"]
                      status:
                        type: string
                        default: disable
                        enum: ["disable","enable","global"]
                      config:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true