/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	"github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/clientset/versioned/scheme"
	v1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	rest "k8s.io/client-go/rest"
)

type ApintoV1Interface interface {
	RESTClient() rest.Interface
	ApintoAuthsGetter
	ApintoDiscoveriesGetter
	ApintoGlobalSettingsGetter
	ApintoOutputsGetter
	ApintoRoutersGetter
	ApintoServicesGetter
	ApintoUpstreamsGetter
}

// ApintoV1Client is used to interact with features provided by the apinto.com group.
type ApintoV1Client struct {
	restClient rest.Interface
}

func (c *ApintoV1Client) ApintoAuths(namespace string) ApintoAuthInterface {
	return newApintoAuths(c, namespace)
}

func (c *ApintoV1Client) ApintoDiscoveries(namespace string) ApintoDiscoveryInterface {
	return newApintoDiscoveries(c, namespace)
}

func (c *ApintoV1Client) ApintoGlobalSettings(namespace string) ApintoGlobalSettingInterface {
	return newApintoGlobalSettings(c, namespace)
}

func (c *ApintoV1Client) ApintoOutputs(namespace string) ApintoOutputInterface {
	return newApintoOutputs(c, namespace)
}

func (c *ApintoV1Client) ApintoRouters(namespace string) ApintoRouterInterface {
	return newApintoRouters(c, namespace)
}

func (c *ApintoV1Client) ApintoServices(namespace string) ApintoServiceInterface {
	return newApintoServices(c, namespace)
}

func (c *ApintoV1Client) ApintoUpstreams(namespace string) ApintoUpstreamInterface {
	return newApintoUpstreams(c, namespace)
}

// NewForConfig creates a new ApintoV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ApintoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ApintoV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ApintoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ApintoV1Client{client}, nil
}

// NewForConfigOrDie creates a new ApintoV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ApintoV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ApintoV1Client for the given RESTClient.
func New(c rest.Interface) *ApintoV1Client {
	return &ApintoV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ApintoV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
