/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/clientset/versioned/scheme"
	v1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ApintoGlobalSettingsGetter has a method to return a ApintoGlobalSettingInterface.
// A group's client should implement this interface.
type ApintoGlobalSettingsGetter interface {
	ApintoGlobalSettings(namespace string) ApintoGlobalSettingInterface
}

// ApintoGlobalSettingInterface has methods to work with ApintoGlobalSetting resources.
type ApintoGlobalSettingInterface interface {
	Create(ctx context.Context, apintoGlobalSetting *v1.ApintoGlobalSetting, opts metav1.CreateOptions) (*v1.ApintoGlobalSetting, error)
	Update(ctx context.Context, apintoGlobalSetting *v1.ApintoGlobalSetting, opts metav1.UpdateOptions) (*v1.ApintoGlobalSetting, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ApintoGlobalSetting, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ApintoGlobalSettingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ApintoGlobalSetting, err error)
	ApintoGlobalSettingExpansion
}

// apintoGlobalSettings implements ApintoGlobalSettingInterface
type apintoGlobalSettings struct {
	client rest.Interface
	ns     string
}

// newApintoGlobalSettings returns a ApintoGlobalSettings
func newApintoGlobalSettings(c *ApintoV1Client, namespace string) *apintoGlobalSettings {
	return &apintoGlobalSettings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the apintoGlobalSetting, and returns the corresponding apintoGlobalSetting object, and an error if there is any.
func (c *apintoGlobalSettings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ApintoGlobalSetting, err error) {
	result = &v1.ApintoGlobalSetting{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ApintoGlobalSettings that match those selectors.
func (c *apintoGlobalSettings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ApintoGlobalSettingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ApintoGlobalSettingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested apintoGlobalSettings.
func (c *apintoGlobalSettings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a apintoGlobalSetting and creates it.  Returns the server's representation of the apintoGlobalSetting, and an error, if there is any.
func (c *apintoGlobalSettings) Create(ctx context.Context, apintoGlobalSetting *v1.ApintoGlobalSetting, opts metav1.CreateOptions) (result *v1.ApintoGlobalSetting, err error) {
	result = &v1.ApintoGlobalSetting{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apintoGlobalSetting).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a apintoGlobalSetting and updates it. Returns the server's representation of the apintoGlobalSetting, and an error, if there is any.
func (c *apintoGlobalSettings) Update(ctx context.Context, apintoGlobalSetting *v1.ApintoGlobalSetting, opts metav1.UpdateOptions) (result *v1.ApintoGlobalSetting, err error) {
	result = &v1.ApintoGlobalSetting{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		Name(apintoGlobalSetting.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apintoGlobalSetting).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the apintoGlobalSetting and deletes it. Returns an error if one occurs.
func (c *apintoGlobalSettings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *apintoGlobalSettings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched apintoGlobalSetting.
func (c *apintoGlobalSettings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ApintoGlobalSetting, err error) {
	result = &v1.ApintoGlobalSetting{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apintoglobalsettings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
