/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/clientset/versioned"
	internalinterfaces "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/informers/externalversions/internalinterfaces"
	v1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/listers/apinto/v1"
	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApintoAuthInformer provides access to a shared informer and lister for
// ApintoAuths.
type ApintoAuthInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ApintoAuthLister
}

type apintoAuthInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApintoAuthInformer constructs a new informer for ApintoAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApintoAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApintoAuthInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApintoAuthInformer constructs a new informer for ApintoAuth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApintoAuthInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().ApintoAuths(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().ApintoAuths(namespace).Watch(context.TODO(), options)
			},
		},
		&apintov1.ApintoAuth{},
		resyncPeriod,
		indexers,
	)
}

func (f *apintoAuthInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApintoAuthInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *apintoAuthInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apintov1.ApintoAuth{}, f.defaultInformer)
}

func (f *apintoAuthInformer) Lister() v1.ApintoAuthLister {
	return v1.NewApintoAuthLister(f.Informer().GetIndexer())
}
