/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/clientset/versioned"
	internalinterfaces "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/informers/externalversions/internalinterfaces"
	v1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/client/listers/apinto/v1"
	apintov1 "github.com/eolinker/apinto-ingress-controller/pkg/kube/apinto/configs/apinto/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApintoOutputInformer provides access to a shared informer and lister for
// ApintoOutputs.
type ApintoOutputInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ApintoOutputLister
}

type apintoOutputInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewApintoOutputInformer constructs a new informer for ApintoOutput type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApintoOutputInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApintoOutputInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredApintoOutputInformer constructs a new informer for ApintoOutput type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApintoOutputInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().ApintoOutputs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApintoV1().ApintoOutputs(namespace).Watch(context.TODO(), options)
			},
		},
		&apintov1.ApintoOutput{},
		resyncPeriod,
		indexers,
	)
}

func (f *apintoOutputInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApintoOutputInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *apintoOutputInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apintov1.ApintoOutput{}, f.defaultInformer)
}

func (f *apintoOutputInformer) Lister() v1.ApintoOutputLister {
	return v1.NewApintoOutputLister(f.Informer().GetIndexer())
}
